name: CLA check

# check if the PR author has signed the CLA

on: [push, pull_request]

jobs:
  cla_check_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependecies
        run: |
          npm install googleapis@39
          npm run actions-build
          git add actions_build/index.js
      - name: CLA check
        uses: ./actions1
        env:
          SHEETS_TOKEN: ${{ secrets.SHEETS_TOKEN }}
          SHEETS_CRED: ${{ secrets.SHEETS_CRED }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
