name: CLA check

# check if the PR author has signed the CLA

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - cla_check

jobs:
  cla_check_job:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependecies
        run: |
          npm install googleapis@39
          npm run actions-build
          git add actions_build/index.js
      - name: CLA check
        uses: ./actions/cla_check
        env:
          SHEETS_TOKEN: ${{ secrets.SHEETS_TOKEN }}
          SHEETS_CRED: ${{ secrets.SHEETS_CRED }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
